[workspace]
resolver = "2"

members = [
    "gg-assets",
    "gg-graphics",
    "gg-graphics-impl",
    "gg-input",
    "gg-main",
    "gg-math",
    "gg-ui",
    "gg-util",
]

[profile.dev]
opt-level = 1

[profile.release]
debug = true
lto = "thin"
