[package]
name = "gg-rtti"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.7.6"
once_cell = "1.13.0"
parking_lot = "0.12.1"
