[package]
name = "gg-expr"
version = "0.1.0"
edition = "2021"

[dependencies]
arc-swap = "1.5.1"
im = "15.1.0"
indenter = "0.3.3"
logos = "0.12.1"
thiserror = "1.0.32"
unicode-width = "0.1.9"
yansi = "0.5.1"
