[package]
name = "gg-expr"
version = "0.1.0"
edition = "2021"

[dependencies]
im = "15.1.0"
indenter = "0.3.3"
logos = "0.12.1"
once_cell = "1.13.1"
thiserror = "1.0.32"
unicode-width = "0.1.9"
yansi = "0.5.1"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "vm"
harness = false