[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-Clink-arg=-fuse-ld=lld", "-Clink-arg=-Wl,--no-rosegment", "-Zshare-generics=y"]

[target.x86_64-pc-windows-msvc]
linker = "rust-lld"
rustflags = ["-Zshare-generics=y"]
